steps:
  integrationArtifactTransport:
    casApiServiceKeyCredentialsId: caspocServiceKeyCred
    integrationPackageId: AlertNotifications
    resourceID: b8a7c674d4644652a04d8805182d78c0
    name: Alert Notifications
    version: 1.0